# Generated by Django 3.2 on 2022-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220322_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
