# Generated by Django 3.2 on 2022-03-26 17:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_serving_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(default=True, max_length=250)),
                ('category_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='categories')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
